#! /bin/sh

export JAVA_HOME=/var/vcap/packages/jre7/jre1.7.0_80
export PATH=$PATH:$JAVA_HOME/bin
export CLASSPATH=$CLASSPATH:/var/vcap/jobs/apiplatform_broker/config
 
case "$1" in
start)
  echo "Starting the APIPlatform Service broker ....."
#  java -jar /var/vcap/packages/apiplatform-broker/openpaas-service-java-broker-apiplatform.jar &
  java -cp "/var/vcap/packages/apiplatform-broker/openpaas-service-java-broker-apiplatform.jar:/var/vcap/jobs/apiplatform_broker/config" org.springframework.boot.loader.JarLauncher &
;;
stop)
  echo "Stopping the WSO2 BAM Server ..."
  pgrep  openpaas-service-java-broker-apiplatform.jar
;;
*)
  echo "Usage: $0 {start|stop}"
exit 1
esac
